name: Build PyTorch Wheels

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-wheel:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      IMAGE_NAME: pytorch-wheel-builder

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo apt-get remove -y '^aspnetcore-.*' '^dotnet-.*' '^temurin-.*' || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build PyTorch wheel for ${{ matrix.arch }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          outputs: type=local,dest=./output-${{ matrix.arch }}

      - name: Upload wheel artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-wheel-${{ matrix.arch }}
          path: ./output-${{ matrix.arch }}/opt/pytorch/dist/*.whl

  release-wheel:
    name: Publish Wheels to GitHub Release
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
    needs: build-wheel
    runs-on: ubuntu-24.04

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/**/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
